### ISSUE TITLE
Question about Injection via symfony instead of Pooler

### ISSUE THREAD

**Issue by lossendae** [pomm-project/pomm-bundle#100]
Hello,

I've been using Pomm for a while, and there is only one thing that really itch me: the need to load models by using the Session.

In services you have to inject a session, most often the default one `@pomm.default_session`
and then:
- load each Model manually
- assign the model to a variable, and use use phpdoc to map the variable to the model class and benefit from nice things like methods from the object in almost all IDE (or a method with the model as return signature)

```php
/**
 * @var $my_model MyModel
 */
$my_model = $session->getSession('default')->getModel(MyModel::class);
$my_model->findThings();
$my_model->doSomethingElse();
```
You can work without it, or some IDE provides external plugins that deal with similar cases (to setup for every project you're using pomm with).

I've played a little with Symfony Flex autowiring and have been able to inject Model classes with the default session directly in services requiring them by declaring the following rule in my `services.yaml`:

```yaml
    _instanceof:
        PommProject\ModelManager\Model\Model:
            public:  true
            calls:
                - [initialize, ['@pomm.default_session']]
```

and modifying the `initialize` method a little to prevent an error : 

```php
public function initialize(Session $session)
    {
       // ...

        if (!$converter_holder->hasConverterName($this->flexible_entity_class)) {
            $converter_holder
                ->registerConverter(
                    $this->flexible_entity_class,
                    new PgEntity(
                        $this->flexible_entity_class,
                        $this->getStructure()
                    ),
                    [
                        $this->getStructure()->getRelation(),
                        $this->flexible_entity_class,
                    ]
                );
        }
    }
```

It works, with this i can directly  autowire my models  via constructor. Less code, i have my type hinting.

But, but i'm curious. What do i lose by not using the session to load my model ?

**Comment by mvrhov** [comment]
You do know that you can register the models as services right? (Read the last chapter of README.md)

**Comment by lossendae** [comment]
I didn't know.

Seems a little daunting to tag each and every models and declare them as services.
I will look in the symfony doc if it's possible to automatically tag all models and model layers.

 Thanks for the pointer.

**Comment by mvrhov** [comment]
You can tag it automatically. But I'm not using autowiring so you'll have to look at the docs on how to do that.

**Comment by lossendae** [comment]
I did find something akin to autotagging in the doc : https://symfony.com/blog/new-in-symfony-3-3-service-autoconfiguration

This may answer all my questions. I will test that and report it here. 
Should i close the issue ?

**Comment by mvrhov** [comment]
IMHO yes.

**Comment by lossendae** [comment]
As feedback,  it indeed works fine with autotagging feature.

Additionally, i had to override the default session builder in yaml config to use mine:

```yaml
    pomm.model_manager.session_builder:
        class: 'App\Model\Name\SessionBuilder'
```

Shouldn't it be precised in the documentation as well ?
