### ISSUE TITLE
The PommProject\SymfonyBridge\PropertyInfo\Extractor\PommExtractor class is deprecated

### ISSUE THREAD

**Issue by maximechagnolleau** [pomm-project/pomm-bundle#112]
Hi,

I use pomm-bundle in a Symfony 4.4 project. Since the 2.3 version of POMM, I have the following notice:

`User Deprecated: The PommProject\SymfonyBridge\PropertyInfo\Extractor\PommExtractor class is deprecated since version 2.3 and will be removed in 3.0. Use the PommProject\SymfonyBridge\PropertyInfo\Extractor\TypeExtractor class instead.`

So I have upgraded pomm-bundle to version 3.0, but I still have this notice message.

Could you please give me an explanation ? Have I missed something and is there a way to avoid these notices ?

Thank you

**Comment by rdavaillaud** [comment]
Well, it seems that this class is still defined as a service in https://github.com/pomm-project/pomm-bundle/blob/3.0.0/sources/lib/Resources/config/services/pomm.yml#L39

@stood I think we just have to remove that in the bundle.

**Comment by maximechagnolleau** [comment]
That's what I think. This class was supposed tout be removed in v3.0

**Comment by Doud63** [comment]
But symfony bridge was already in version 3, and deprecation is not removed?
This error is blocking

**Comment by rdavaillaud** [comment]
How is it blocking? Isn't it just a deprecation notice?

The class itself is not used anymore, just declared in the service container, with a deprecation notice and a class_alias https://github.com/pomm-project/pomm-symfony-bridge/blob/3.0.0/sources/lib/PropertyInfo/Extractor/PommExtractor.php

**Comment by maximechagnolleau** [comment]
That's not blocking. But deprecation messages still appears without any reason.

**Comment by Doud63** [comment]
Sorry for the time of my answer.
I work in PHP 8, and i have this error in test environment 
`Error : Class "PommProject\SymfonyBridge\PropertyInfo\Extractor\PommExtractor" not found`

Thanks for your Pull Request, rdavaillaud
