### ISSUE TITLE
Add EXPLAIN in profiler

### ISSUE THREAD

**Issue by chanmix51** [pomm-project/pomm-bundle#12]
The pomm symfony bridge [has been updated](https://github.com/pomm-project/pomm-symfony-bridge/commit/d7e6777e4afb1a0842cd7a15b7594f84a0f9f840) with a controller + view to perform EXPLAIN on statements from the profiler. The changes have been commited in a `explain` branch to ovoid breaking PommBundle.

**Comment by chanmix51** [comment]
I have fixed the issue with the `DateTime` as parameter. Is it ok for you we merge our changes in master branch ?

**Comment by sanpii** [comment]
Merged :smile:
