### ISSUE TITLE
Unrecognized option "web_profiler" under "pomm"

### ISSUE THREAD

**Issue by Monpetitjules** [pomm-project/pomm-bundle#16]
Hi,
Just to let you know what error message I got after updating pomm through composer : 

    - Removing pomm-project/foundation (2.0-beta-1)
    - Installing pomm-project/foundation (2.0.0-beta.2)
      Loading from cache

    - Removing pomm-project/model-manager (2.0-beta-1)
    - Installing pomm-project/model-manager (2.0.0-beta.2)
      Loading from cache

    - Updating pomm-project/cli (dev-master d3f8eda => 2.0.0-beta.2)
      Checking out edf5b8b50bff102522988ce39eceaff89d1b309f

    - Updating pomm-project/pomm-symfony-bridge dev-master (e034648 => ca32a31)
      Checking out ca32a31c3790362410a5195583cfc7147e1f261c

    - Updating pomm-project/pomm-bundle dev-master (1a7b1df => 53233a5)
      Checking out 53233a5ace1a27921c79cfccf7f622daf855a8f7
                                                                                 
    [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
    Unrecognized option "web_profiler" under "pomm"                                

After commenting the following lines in app/config/config_dev.yml, everything was back to normal.

    pomm:
        web_profiler: true

Hope it helps.

**Comment by stood** [comment]
This (https://github.com/pomm-project/pomm-bundle/commit/9df5afcc7c491cb92ae61891075de6bbfe742c3c) delete option web_profiler

Delete this option in your config_dev.yml, now it's automatic

**Comment by chanmix51** [comment]
:+1:
