### ISSUE TITLE
No pooler registered for type 'model'

### ISSUE THREAD

**Issue by belka-ew** [pomm-project/pomm-bundle#18]
Hi,

well, my real problem with Pomm2 is the following one. I have the following controller:

```
<?php
namespace WpBundle\Controller\Frontend;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use WpBundle\Controller\Api\FrontendController;

class TestimonialsController extends FrontendController
{
	public function indexAction() {
        $pomm = $this->get('pomm')['caraus'];

		$testimonials = $pomm->getModel('WpBundle\Model\Testimonial\Testimonial')
            ->findAll();

		return $this->render('WpBundle:frontend/testimonials:index.html.smarty', $this->mergeLayout(
			array(
				'testimonials' => $testimonials,
			),
			'testimonials'
		));
	}
}
```
And I get the error:
```
 No pooler registered for type 'model'. Poolers available: {prepared_query, query_manager, converter, observer, inspector, listener}.
500 Internal Server Error - FoundationException
```
I used the standard configuration from the quick setup tutorial:
routing.php:
```
<?php
use Symfony\Component\Routing\RouteCollection;

$collection = new RouteCollection();

$collection->addCollection(
	$loader->import('@PommBundle/Resources/config/routing.yml')
);

$collection->addCollection(
	$loader->import('@WpBundle/Resources/config/routing.php')
);

return $collection;
```
config.php:
```

// Pomm Configuration
$container->loadFromExtension('pomm', array(
    'configuration' => array(
        'caraus' => array(
            'dsn' => 'pgsql://%database.user%:%database.password%@%database.host%:%database.port%/%database.name%',
        ),
    ),
    'logger' => array(
        'service' => '@logger',
    ),
));
```
The model is generated. I found out, that all poolers that are listed in the error message (prepared_query, query_manager, converter, observer, inspector, listener) are in the Foundation bundle, and the model pooler is in the model-manager bundle. So I suppose that the pooler isn't loaded somehow (sorry for the my terminology; I just try to explain as I can). Similar code without Symfony, with getModel works as expected. If I use getInspector instead of getModel the loading goes further throwing other exceptions, but I suppose it isn't the way it should work.
It is the reason I can't work with Pomm2 now

**Comment by sanpii** [comment]
Hello,

For using model manager, you should enable the corresponding ``SessionBuilder``: https://github.com/pomm-project/ModelManager#installation

Try with this config.php:

    // Pomm Configuration
    $container->loadFromExtension('pomm', array(
        'configuration' => array(
            'caraus' => array(
                'dsn' => 'pgsql://%database.user%:%database.password%@%database.host%:%database.port%/%database.name%',
                'class:session_builder' => '\PommProject\ModelManager\SessionBuilder',
            ),
        ),
        'logger' => array(
            'service' => '@logger',
        ),
    ));

**Comment by chanmix51** [comment]
May we close this issue ?

**Comment by belka-ew** [comment]
I'm ashamed now... I thought that since the ModelManager is a dependency, it would be somehow intergrated and work automatically and I couldn't associate the lines
```
my_db2:
            dsn: 'pgsql://%db_user2%:%db_password2%@%db_host2%:%db_port2%/%db_name2%'
            class:session_builder: '\PommProject\ModelManager\SessionBuilder'
```
with my issue. More detailed error message is anyway good.
The bundle works now like a charm. Thanks.

**Comment by chanmix51** [comment]
As I said, it is always good for us to see where newcommers do meet the real world (c) so we can make things as easy as possible. 

Thank you for your feedback, do not hesitate to share good and bad sides of your experience with Pomm2 with us.
