### ISSUE TITLE
Security user provider

### ISSUE THREAD

**Issue by belka-ew** [pomm-project/pomm-bundle#20]
Hey,

I'm writing currently user authentication. I saw that there was a PommUserProvider for Pomm1, but I haven't found something like this for Pomm2. Should I implement it and make a pull request? I would also write a short wiki page with a description how it could be used. Another idea, since I will write a User class, I could also create a separate bundle for that (something like FosUserBundle for Pomm2, I don't use FosUserBundle since it has some restrictions I don't like.

Regards
Eugene

**Comment by chanmix51** [comment]
Hi Eugene,

I do not think this should be part of the PommBundle nor should be a PommProject related repo. Imho this should be a third party package you could publish under your own vendor. Of course we will add a link to it on Pomm's website. Would that do the job ?

**Comment by belka-ew** [comment]
yes, for sure. I was just wondering if there is a need at least to port the PommUserProvider (https://github.com/chanmix51/PommBundle/blob/master/Security/User/PommUserProvider.php) from Pomm1 to Pomm2.
Maybe I won't then write an extra bundle but describe somewhere how to get the user authentication working with PostgreSQL.
Thanks for your quick answer!
