### ISSUE TITLE
create a realease please and a branch alias and a roadmap

### ISSUE THREAD

**Issue by cordoval** [pomm-project/pomm-bundle#21]
also hide the wiki please if not used

**Comment by chanmix51** [comment]
A roadmap in the README is a good idea. 
There is a a branch alias `"pomm-project/pomm-bundle": "2.0.*@dev"`

**Comment by sanpii** [comment]
> A roadmap in the README is a good idea.

I dislike this idea, I prefer using an issue for this.

**Comment by chanmix51** [comment]
:+1:

**Comment by cordoval** [comment]
that is exactly what i meant by roadmap, closing now since you got the idea :older_man:
