### ISSUE TITLE
The service "data.collector.time" has a dependency on a non-existent parameter "data_collector.time.class"

### ISSUE THREAD

**Issue by belka-ew** [pomm-project/pomm-bundle#24]
After the last updates I get the following error in production environment in Symfony:

[Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]                                                                                                                         
  The service "data.collector.time" has a dependency on a non-existent parameter "data_collector.time.class". Did you mean one of these: "data_collector.templates", "data_collector.security.class"?

I get it only for production. Dev Environment works as expected. Adding the following line to parameters.php (in my case) seems to fix it:
'data_collector.time.class' => 'Symfony\\Component\\HttpKernel\\DataCollector\\TimeDataCollector'

(just a temorary fix).

**Comment by sanpii** [comment]
Fixed in 82c7bca07e9a16122d9eb5cf208305e2a4cc945f

Thank you.
