### ISSUE TITLE
Options doesn’t work

### ISSUE THREAD

**Issue by sanpii** [pomm-project/pomm-bundle#26]
```php
/**
 * @ParamConverter(options={"model": "Test"})
 */
```

``$configuration->getOptions()`` in [EntityParamConverter.php#L51](https://github.com/pomm-project/pomm-bundle/blob/master/sources/lib/Request/ParamConverter/EntityParamConverter.php#L51) is always empty.

**Comment by stood** [comment]
Declare your variable in your ParamConverter
