### ISSUE TITLE
All connections should be closed on shutdown

### ISSUE THREAD

**Issue by stof** [pomm-project/pomm-bundle#30]
See the discussion in https://github.com/doctrine/DoctrineBundle/pull/366 for more details, as the reason is the same than for Doctrine connections

**Comment by chanmix51** [comment]
Normally, handler connection is closed when the session is wiped from memory by the garbage collector (see [here](https://github.com/pomm-project/Foundation/blob/master/sources/lib/Session/Session.php#L82). We did not encounter the connection limit problem during test so far.

**Comment by stof** [comment]
The point is, the session can stay in memory longer than necessary on shutdown, because the refcounting might not be enough to destruct the Symfony container (and so all services inside it which have been initialized). See https://github.com/symfony/symfony/issues/13448 for a discussion about improving it.
