### ISSUE TITLE
Twig dependency

### ISSUE THREAD

**Issue by taavit** [pomm-project/pomm-bundle#35]
Hi,
I'm working on some API with stripped symfony distribution. Currently I've removed Twig Bundle, as I don't need this, but pomm-bundle requires it to work. Is it possible to make twig.loader dependency conditional, and set this only if Twig is used?

**Comment by sanpii** [comment]
You’re right, I can probably move `pomm.data_collector` and `pomm.twig_extension` services to `profiler.yml`.

**Comment by taavit** [comment]
I think it should depends on web_profiler.debug_toolbar service rather then data_collector.time.class parameter like profiler.yml itself, because pomm.twig_extension only for views, but profiling data should be still available even when toolbar is not used.

**Comment by sanpii** [comment]
> I think it should depends on web_profiler.debug_toolbar service

No. I played with the dependency container and I can’t do that.

Can you try the PR #37?

**Comment by sanpii** [comment]
Fixed in fc32e88503dc2eb43137c39e31a109b903311423
