### ISSUE TITLE
Closing connection prevent cleaning session shutdown

### ISSUE THREAD

**Issue by chanmix51** [pomm-project/pomm-bundle#40]
Session's clients need to access the connection to shutdown properly. If the connectin [is closed](https://github.com/pomm-project/pomm-bundle/blob/master/sources/lib/PommBundle.php#L62) by the bundle, the session fails at shutting down the client holder.

```
PHPUnit 4.7.3 by Sebastian Bergmann and contributors.
.

Time: 842 ms, Memory: 32.25Mb

OK (1 test, 3 assertions)

PHP Warning: pg_connection_status(): 1153 is not a valid PostgreSQL link resource.
```

**Comment by sanpii** [comment]
In [foundation/Session/Connection.php](https://github.com/pomm-project/Foundation/blob/master/sources/lib/Session/Connection.php), after `pg_close` set `Connection::handler` to `null` probably fixed this warning.

I can make the PR if you are agree.

**Comment by chanmix51** [comment]
Ah ah, that's what I did in the `close_session` branch, but it still does not shutdown the session properly and when session::__destruct is called, connection is re-opened to deallocate prepared statements which does not exist in the new session.

**Comment by chanmix51** [comment]
I have set up a [close_connection](https://github.com/pomm-project/Foundation/tree/close_session) branch on Foundation with a new API to close sessions from a `Pomm` instance. Would you mind having a look at it ?

**Comment by mvrhov** [comment]
IMO, the session should use new connection, not the one used by pomm. The problem is that if there is an transaction error, all further statements will be ignored. and thus session save will also fail.

**Comment by chanmix51** [comment]
You mean merging the `pomm_shutdown` branch with the new Connection system 2 months ago did not fix the problem ?

**Comment by sanpii** [comment]
@chanmix51 I don’t know. This is your issue, is it fix?

I can test, but I need the unit test to reproduce the bug.

**Comment by mvrhov** [comment]
Oh. :blush: I was looking for something different and found this one. When talking about session in this thread I didn't realize, that the the session refers to the pomm session and not the application session. I deeply apologize.

**Comment by chanmix51** [comment]
ouf :) don't mind, that's ok. @sanpii can we close this one ?
