### ISSUE TITLE
Default directory structure without 'Mydb\PublicSchema'

### ISSUE THREAD

**Issue by shamotj** [pomm-project/pomm-bundle#42]
Pomm generates model, structure and other files to directory structure Connectionalias\Schema. If I have only one connection to DB, which I believe is very common scenario, I think that there could be something like "default connction" which will ommit this in namespace and in path. In result there will be only src/AppBundle/Model/ instead of src/AppBundle/Model/Mydb/PublicSchema/.

**Comment by sanpii** [comment]
This is a good idea (I think we talked about it on IRC), but this issue is for [pomm-project/Cli](https://github.com/pomm-project/Cli).

**Comment by shamotj** [comment]
@sanpii Yes you are right. I'm closing this one and new one in correct project is here https://github.com/pomm-project/Cli/issues/31.

**Comment by sanpii** [comment]
Thank you :smiley:
