### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by yann-eugone** [pomm-project/pomm-bundle#43]
Hi all,

I'm trying to use Pomm in a Symfony project (for testing purpose), but I'm stuck right at the beginning of my journey as I'm not able to install the Bundle...

> [symfony] : 2.7.3

Running : 

    $ composer require pomm-project/pomm-bundle 2.0.*@dev

Output me the following : 

```
  Problem 1
    - Installation request for pomm-project/pomm-bundle 2.0.*@dev -> satisfiable by pomm-project/pomm-bundle[2.0.x-dev].
    - pomm-project/pomm-bundle 2.0.x-dev requires pomm-project/foundation 2.0.*@dev -> no matching package found.
```

I believe this may be caused by my minimum-stability value : `stable` (which is the default value), but **I do not want to change it**.

Anybody has an idea of what I am doing wrong ?

**Comment by chanmix51** [comment]
Then you will have to specify all Pomm bundle’s dependencies manually in your `composer.json` file.

```
        "pomm-project/pomm-bundle": "2.0.*@dev",
        "pomm-project/pomm-symfony-bridge": "2.0.*@dev",
        "pomm-project/foundation": "2.0.*@dev",
        "pomm-project/model-manager": "2.0.*@dev",
        "pomm-project/cli": "2.0.*@dev"
```

**Comment by yann-eugone** [comment]
Many thanks.
I believe this issue is due to the fact that Pomm is not considered as stable yet.
But the fact is that if I upgrade the minimum-stability for my whole project, all the libraries will get updated, and this is not what we usually want (this is why the "@dev" stand for, am I right?).
We should at least document this in the installation process of this bundle.
If you wan't me to, I can create a PR to the doc that explain this.

**Comment by chanmix51** [comment]
It would be appreciated :+1:
