### ISSUE TITLE
Flexible entity serializer normalizer

### ISSUE THREAD

**Issue by SebLours** [pomm-project/pomm-bundle#49]
For my project, i create a normalizer for the Symfony serializer.
It improves serializer performance and use Pomm logic for FlexibleEntity instances.

https://gist.github.com/SebLours/2b6cb67ce3f99c35d146

Did you think, it can be add to the bundle ?

**Comment by sanpii** [comment]
It’s a good idea to make symfony serializer works with `FlexibleEntity`, but I think it’s better to do this with implementing the `JsonSerializable` interface.

**Comment by SebLours** [comment]
You're right when you want to serialize in json, but the symfony serializer not only supports json format.

**Comment by sanpii** [comment]
You right. You can make a PR for the [pomm-symfony-bridge](https://github.com/pomm-project/pomm-symfony-bridge) project.

**Comment by SebLours** [comment]
Here it is
https://github.com/pomm-project/pomm-symfony-bridge/pull/22

**Comment by sanpii** [comment]
https://github.com/pomm-project/pomm-symfony-bridge/pull/22 merged.
