### ISSUE TITLE
Relations in Symfony Form

### ISSUE THREAD

**Issue by Hadrien45** [pomm-project/pomm-bundle#52]
Hi,

I start to use Pomm2 with Symfony3 and I have a question about "relations" in form.
I have 2 tables "book" and "author". In the book form I can choose one author in a list.

With Doctrine, I add the following lines : 
<pre>
$builder->add('authors', EntityType::class, array(
    'class' => 'AppBundle:Author',
    'choice_label' => 'fullname',
));
</pre>

The same thing exists in Pomm ?
Thanks

**Comment by sanpii** [comment]
There is a PR about this, in the symfony bridge: https://github.com/pomm-project/pomm-symfony-bridge/pull/17

**Comment by Hadrien45** [comment]
Thanks for your answer.
Do you know when this PR will be merged ? 
I saw quickly the code and I think it not compatible with Symfony 3 (ObjectChoiceList class has been removed in favor of  ArrayChoiceList, ...)

**Comment by stood** [comment]
This PR is not compatible with SF3 Work in progress :)

But for sf3 use  "choiceType" working :
```
$builder->add('category', ChoiceType::class, [
            'choices' => $iterator,
            'choice_label' => function($elt) {
                return $elt->getTitle();
            },

            'placeholder' => 'Choose category,
            'choice_value' => function($elt) {
                if ($elt !== null)
                    return $elt->getCategoryId();
            },
            'required' => true
        ])
```
Where $iterator is Iterator of pomm, for example : 
Model->findAll();

**Comment by Hadrien45** [comment]
Thanks for your help and good luck for the PR ;)
