### ISSUE TITLE
Unique "Obejct" Validator in Pomm

### ISSUE THREAD

**Issue by Hadrien45** [pomm-project/pomm-bundle#53]
Hi,

Following https://github.com/pomm-project/pomm-bundle/issues/52, I have an another question about Pomm and Symfony Form.
Doctrine have a UniqueEntityValidator, I don't find a similar thing in Pomm. 
I create a gist https://gist.github.com/Hadrien45/154f981ba3daf8149435aaebcb48d9c4 to solve my problem. However, I'm not an expert in Symfony and Pomm, so I don't know if it a "good way" to do that.

Thanks

**Comment by mvrhov** [comment]
@Hadrien45: Create a PR and this might get merged. Although having the PR on pomm-project/pomm-symfony-bridge would be better as then it could also be used from silex
