### ISSUE TITLE
Still not stable?

### ISSUE THREAD

**Issue by rdavaillaud** [pomm-project/pomm-bundle#56]
Hi,

Pomm-bundle is still not stable?

**Comment by chanmix51** [comment]
:fearful:

**Comment by rdavaillaud** [comment]
Well, no offense here, the README.md is simply misleading.  

I was just afraid, alone behind my desk, asking to myself : "What am I going to do?!"  
Then, I have shut down my computer and thougth about myself.

**Comment by rdavaillaud** [comment]
And, I am not yet familiar with composer stability consideration.

**Comment by chanmix51** [comment]
PommBundle is stable for a long time. It is just a matter of tagging. I am going to chat about that with @sanpii tonight. It should be tagged as stable.

**Comment by rdavaillaud** [comment]
Yep, I figured that out after my dumb question.

The readme still have to be updated, as Pomm2 is stable too, right?

**Comment by chanmix51** [comment]
The stability tag must be set in order to tell composer the bundle is stable. So this is an isse :+1:

**Comment by sanpii** [comment]
Voilà, the bundle is stable :smile: 

c8351790628ee5d7d3056e23403176614fba6710

**Comment by mvrhov** [comment]
for bundle to behave correctly in 3.x at least my #54 should be merged and then new version tagged.

**Comment by sanpii** [comment]
@mvrhov Thank you for reminding me.

**Comment by mvrhov** [comment]
Also new tag would be wonderful :) So there is officially a version that works on symfony 3
