### ISSUE TITLE
impossible to use a session builder as a service

### ISSUE THREAD

**Issue by lunika** [pomm-project/pomm-bundle#76]
I updated pomm-bundle to version 2.3.0 and it is impossible for me to use the new `session_builder`.

My service definition is not yet registered in the container builder when the `PommExtension` try to use it [here](https://github.com/pomm-project/pomm-bundle/blob/master/sources/lib/DependencyInjection/PommExtension.php#L68)

**Comment by mvrhov** [comment]
You have to change the order of the bundles.

**Comment by lunika** [comment]
Nop this changes nothing I already tried and my services are not loaded from my bundle but from the AppKernel

**Comment by mvrhov** [comment]
I'd say that this is unsupported usecase then. 
I've never used Symfony without the bundles. So I can't really help there. I don't know if that would work but if the compiler pass can be registered there this would be another way of changing this property.

**Comment by lunika** [comment]
wow then PommBundle can't be used with a bundle less symfony application and the `class:session_builder` config key musn't be dropped in version 3.0

**Comment by sanpii** [comment]
I don’t sure to understand the problem. Do you have a minimalist application example can I use to reproduce this issue?

**Comment by lunika** [comment]
My services are not declared in a bundle but in the `app/config/` directory. That's all. 
You will also have this error if your `AppBundle` is register before the `PommBundle` in `AppKernel::registerBundles`

**Comment by lunika** [comment]
clone this repo https://github.com/lunika/pomm-sample you will have the error

**Comment by sanpii** [comment]
Ok, thank you for this sample, it’s rewire my brain in the right way :)

PR merged.
