### ISSUE TITLE
Warning raised with SF 3.3 in ContainerModelLayerPooler 

### ISSUE THREAD

**Issue by benoitaudicsvd** [pomm-project/pomm-bundle#81]
Because the property `serviceMap` can be null the function `array_key_exists` raise a warning in class [`ContainerModelLayerPooler`](https://github.com/pomm-project/pomm-bundle/blob/2.3.0/sources/lib/Model/ContainerModelLayerPooler.php#L47).

We are using PommBundle 2.3.0

**Comment by mvrhov** [comment]
this was already fixed in #73, but @sanpii didn't want to merge it into 2.3-

**Comment by sanpii** [comment]
This is also fix in master, via #78
