### ISSUE TITLE
Support symfony4

### ISSUE THREAD

**Issue by sanpii** [pomm-project/pomm-bundle#86]
* [x] https://github.com/pomm-project/pomm-symfony-bridge/issues/31
* [x] https://github.com/pomm-project/pomm-symfony-bridge/pull/33
* [x] https://github.com/pomm-project/Cli/pull/43
* [x] #90 
* [x] #92

**Comment by stood** [comment]
And add this point #87  ? :)

**Comment by stood** [comment]
https://github.com/pomm-project/pomm-symfony-bridge/pull/32
