### ISSUE TITLE
Custom converter

### ISSUE THREAD

**Issue by skyhell59** [pomm-project/pomm-bundle#99]
Here is my problem, I created a table with a field having an ENUM type. When I try to insert my object into a database via the insertOne method of the model manager. I have to create my own converter but what should I put in it?

Here is an example of the created type:
CREATE TYPE my_type AS ENUM ('type1', 'type2' type3 ');

**Comment by chanmix51** [comment]
This place is intended for bug reports, not for support. For free support assistance, would you please mind asking your question on [stack-overflow](https://stackoverflow.com/questions/tagged/pomm)? Be sure to tag your question with the `pomm` tag. Thank you.
